### ISSUE TITLE
There is no display of textures for some items

### ISSUE THREAD

**Issue by idkwhoisit** [DM-Earth/create-fabric-dme-edition#1]
### Describe the Bug

There is no display of textures for some items:
1)water wheel
2)large water wheel
3)crushing wheel
4)copper valve handle
5)mechanical roller
6)fly wheel
7) empty blaze burner and blaze burner in inventory
8)display link
9)nixie tube

### Reproduction Steps

1. im install sodium 0.5.3, indium 1.0.27, iris 1.6.9 
2. im launch the game and create new world,  it's fine
3. try to use some block of list, and  didn't see the texture
4. im try to install the Oculus-Flywheel-Compat, but it didn't help
5. try to change versions of the sodium and indium, that didn't help either
6. try to disable shaders

### Expected Result

I want you to fix this, or tell me what the problem might be

### Screenshots and Videos

![Screenshot_2](https://github.com/DM-Earth/create-fabric-dme-edition/assets/61099534/e125a8ef-3f98-4b60-bfa4-8ff060d89db1)
![Screenshot_3](https://github.com/DM-Earth/create-fabric-dme-edition/assets/61099534/61771ab5-2048-44f9-bffa-181e85d2a476)
![Screenshot_4](https://github.com/DM-Earth/create-fabric-dme-edition/assets/61099534/6cc8b967-675c-47d4-b06f-b35ff2f18f04)

### Operating System

windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![Screenshot_5](https://github.com/DM-Earth/create-fabric-dme-edition/assets/61099534/51ee24b2-4387-46e0-b350-d831f1e8f051)
![Screenshot_6](https://github.com/DM-Earth/create-fabric-dme-edition/assets/61099534/fbf35369-be31-4697-ab94-de6e9f7c7b14)

**Comment by TexBlock** [comment]
Does turning off shader have this problem / uninstalling Iris-Flywheel-Compat still have this problem?

**Comment by TexBlock** [comment]
[this](https://modrinth.com/mod/create-fabric-dme-edition/version/0.5.1-d-build.8+mc1.20.1) version may be fixed?

**Comment by KonSola5** [comment]
No (downloaded the latest patch "build-8") and aforementioned items/blocks do not render with or without Sodium.
![wheel](https://github.com/DM-Earth/create-fabric-dme-edition/assets/125081901/5dee9196-77c8-47c0-920c-b79cc00596b9)

Mod list:
![mods](https://github.com/DM-Earth/create-fabric-dme-edition/assets/125081901/b339cb8c-d6fa-468b-8ebc-74e9619cec3a)

**Comment by AlphaMode** [comment]
https://github.com/DM-Earth/create-fabric-dme-edition/blob/321a51ce06db4e2f801a006055866bea3cc8bc7c/src/main/resources/assets/create/models/block/crushing_wheel/block.json#L3C5-L3C5 this should be ```"loader":``` not ```"porting_lib:loader":``` <@864003308632408115> this includes all other references like this. Doing this will probably fix it

**Comment by idkwhoisit** [comment]
> Does turning off shader have this problem / uninstalling Iris-Flywheel-Compat still have this problem?

Yep, without shaders and uninstalling Iris-Flywheel-Compat, still have this problem

**Comment by idkwhoisit** [comment]
> [this](https://modrinth.com/mod/create-fabric-dme-edition/version/0.5.1-d-build.8+mc1.20.1) version may be fixed?

ok,  I'll try a little later

**Comment by KonSola5** [comment]
> https://github.com/DM-Earth/create-fabric-dme-edition/blob/321a51ce06db4e2f801a006055866bea3cc8bc7c/src/main/resources/assets/create/models/block/crushing_wheel/block.json#L3C5-L3C5 this should be `"loader":` not `"porting_lib:loader":` <@864003308632408115> this includes all other references like this. Doing this will probably fix it

Yes, it does fix it (this can be done right now in a resource pack)
![wheeeeel](https://github.com/DM-Earth/create-fabric-dme-edition/assets/125081901/d95d1650-94dc-4ec9-af26-20afda8b37bd)

**Comment by KonSola5** [comment]
Though with this "fix" applied, Waterwheel renders in hand and as a dropped item, but crashes the game upon being placed.
https://mclo.gs/HUYNzKl

**Comment by TexBlock** [comment]
> Though with this "fix" applied, Waterwheel renders in hand and as a dropped item, but crashes the game upon being placed. https://mclo.gs/HUYNzKl

This is a problem with PortingLib `2.1.1142+1.20-entity-refactor`, now fixed in PortingLib `2.1.1142+1.20-entity-refactor` (?) I'll upgrade to `2.1.1142+1.20-entity-refactor` later

**Comment by TexBlock** [comment]
This has been fixed in the latest build, I'll upload it to modrinth/curseforge later.
