### ISSUE TITLE
Fluid containers can't accept liquids

### ISSUE THREAD

**Issue by KonSola5** [DM-Earth/create-fabric-dme-edition#11]
### Describe the Bug

Basins, Tanks, Item Drains and Spouts can't accept liquids, and no fluid pipes connect to them.
Clicking with a bucket is also not an option.

### Reproduction Steps

1. Place a Basin, Tank, Item Drain or a Spout.
2. Either right-click the container with a bucket of fluid, or try to connect some fluid pipes to the basin.
3. Clicking with a bucket does not fill the container, pipes don't connect either.

### Expected Result

Pipes should connect to Basins, Tanks, Item Drains and Spouts and clicking with a bucket should input the liquid.

### Screenshots and Videos

![fluid](https://github.com/DM-Earth/create-fabric-dme-edition/assets/125081901/216a2823-5cfb-4b12-b391-be4e5a39164f)

Here's also a screenshot with Modern Dynamics pipes and a Kibe Tank filled with water.
![modern_dynamics](https://github.com/DM-Earth/create-fabric-dme-edition/assets/125081901/b4188292-8945-49e4-8bbc-2010b7797f2d)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TexBlock** [comment]
fixed in Patch 3
