### ISSUE TITLE
You should have done this, instead of this.

### ISSUE THREAD

**Issue by PSGitHubUser1** [DM-Earth/create-fabric-dme-edition#12]
I want to ask the repo author that can you support the actual devs of Create Fabric, instead of updating this

I mean I am glad that you made this fork but instead of doing this you could have help the orginal Create Fabric devs if you know how to fix this SH!T Sodium 0,5.x issues...

And helping it may give you a Contributor tag in that repo. Although, I am just suggesting.. not forcing you to do that...

**Comment by PSGitHubUser1** [comment]
Or open a PR in original Create Fabric..

**Comment by TexBlock** [comment]
Fix compatibility issue with sodium 0.5.x need to make flywheel compatible with sodium 0.5.x ([someone already turned on a PR](https://github.com/Jozufozu/Flywheel/pull/214)).
