### ISSUE TITLE
Game says "Resource Failed to Load" and crashes

### ISSUE THREAD

**Issue by PSGitHubUser1** [DM-Earth/create-fabric-dme-edition#13]
### Describe the Bug

This always happens whenever I open the game. 

### Reproduction Steps

1. Install All req. mods
2. Start the game
3. See the issue
4. Game crashes whenever I click on that Create button.

### Expected Result

It should have loaded the resources

### Screenshots and Videos

See on top right corner...
![](https://cdn.discordapp.com/attachments/976100492243501106/1168460482345181234/image.png?ex=6551d89f&is=653f639f&hm=40b28c0046e9ae046559351ebc9624e082b9056ea4fda7e9c1e37ddb8cfe3926&)

### Crash Report or Log

https://gist.github.com/PSGitHubUser1/74653ffd2428d57e3bbfbee883ee4fbd

### Operating System

Kali Linux and Windows 11 (faces same thing on both OSes)

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

create-fabric-0.5.1-d-build.9+mc1.20.1.jar
fabric-api-0.90.4+1.20.1.jar
Hephaestus-1.20.1-3.6.3.232.jar
indium-1.0.27+mc1.20.1.jar
iris-mc1.20.1-1.6.10.jar
sodium-fabric-mc1.20.1-0.5.3.jar

**Comment by PSGitHubUser1** [comment]
How you fixed it? By updating the rei compatibility or portlib

Or else? 

'cause there are only 3 commits in this week

**Comment by TexBlock** [comment]
> How you fixed it? By updating the rei compatibility or portlib
> 
> Or else?
> 
> 'cause there are only 3 commits in this week

Patch 3 maybe fix this issue
