### ISSUE TITLE
Create DM-Earth crashes with Steam N' Rails and Big Cannons (separate issues)

### ISSUE THREAD

**Issue by vukkax** [DM-Earth/create-fabric-dme-edition#2]
### Describe the Bug

Create DM-Earth crashes while loading the game if it is used alongside Steam N' Rails or Big Cannons (tried separate times with each mod). Not using any other mods apart from Quilted Fabric API. Here's the crash report for the two mods:

[crash-with-bigcannons.txt](https://github.com/DM-Earth/create-fabric-dme-edition/files/12838127/crash-with-bigcannons.txt)
[crash-with-railways.txt](https://github.com/DM-Earth/create-fabric-dme-edition/files/12838128/crash-with-railways.txt)

### Reproduction Steps

1. Install Create DM-Earth
2. Install _Steam N' Rails addon_ **OR** _Create: Big Cannons_
3. Game crashes
...

### Expected Result

The expected result was the game to load properly instead of crashing.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/DM-Earth/create-fabric-dme-edition/assets/108903683/f632aa8e-68cd-470d-8b51-633dfa9ea6fe)

**Comment by vukkax** [comment]
Seems to crash with any Create Mod Addon, not only those two.

**Comment by TexBlock** [comment]
> Seems to crash with any Create Mod Addon, not only those two.

They are need update PortingLib version to `2.1.1142+1.20-entity-refactor`, not this mod issue.

I ask to AlphaMode about Create Fabric not compat Hephaestus, he say:
![0ccf19c58c141efca086ceb46f8f413a](https://github.com/DM-Earth/create-fabric-dme-edition/assets/65154269/fad79e25-00cd-4732-b871-8b5d0b6b169e)

**Comment by TexBlock** [comment]
move to #4
