### ISSUE TITLE
dashloader incompatible with create dm edition

### ISSUE THREAD

**Issue by loti1234** [DM-Earth/create-fabric-dme-edition#5]
### Describe the Bug

game crash

### Reproduction Steps

1. launch latest create dm edition with latest dashloader

### Expected Result

I want you to fix this, or tell me what the problem might be

### Screenshots and Videos

![image](https://github.com/DM-Earth/create-fabric-dme-edition/assets/140719665/b3c9b561-665a-409f-be80-289c5b21a566)

### Crash Report or Log

https://gist.github.com/loti1234/97001d2527847d673112b55a1b1ccdec

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

listed in the crash below

**Comment by TexBlock** [comment]
same #1034, not create fabric issues
