### ISSUE TITLE
Cogwheels don't make any sounds when placed normally

### ISSUE THREAD

**Issue by KonSola5** [DM-Earth/create-fabric-dme-edition#6]
### Describe the Bug

Cogwheels don't make any sounds when placed normally.
They emit sounds only when the cogwheel is placed using Create's placement assist.

### Reproduction Steps

1. Place a Cogwheel or a Large Cogwheel.
2. Observe - no sounds and the block placement hand animation is not played.
3. Place a Cogwheel next to a Cogwheel with Placement Assist.
4. Observe - sound is emitted and the block placement hand animation is played.

### Expected Result

Cogwheel placement should emit sounds and play the block placement hand animation in both cases.

### Screenshots and Videos

https://github.com/DM-Earth/create-fabric-dme-edition/assets/125081901/fce28e73-da63-4150-bc25-f08dbdd628e3

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TexBlock** [comment]
fixed in Patch 3
