### ISSUE TITLE
certain items are invisible

### ISSUE THREAD

**Issue by glittermutt** [DM-Earth/create-fabric-dme-edition#7]
### Describe the Bug

yeah, that's about it, a bunch of items are missing textures and models

### Reproduction Steps

1. install the mod
2. there are no textures
3. profit

### Expected Result

there should be textures :c

### Screenshots and Videos

![2023-10-10_16 55 48](https://github.com/DM-Earth/create-fabric-dme-edition/assets/134949309/f3c4d48e-baff-4bf1-9c25-c6dc9d43d5f9)
![2023-10-10_16 55 51](https://github.com/DM-Earth/create-fabric-dme-edition/assets/134949309/5102bda9-6702-49a3-bbd9-881c580de0ce)
![2023-10-10_16 55 55](https://github.com/DM-Earth/create-fabric-dme-edition/assets/134949309/cd05de08-cac7-4087-9725-64d19a6623b8)
![2023-10-10_16 55 56](https://github.com/DM-Earth/create-fabric-dme-edition/assets/134949309/3ddcb2bb-e03c-4c37-ad65-e231db0929d0)
![2023-10-10_16 56 00](https://github.com/DM-Earth/create-fabric-dme-edition/assets/134949309/4e452c47-f9fa-4eb1-866b-20e2a4096a7c)

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TexBlock** [comment]
non-replicable

**Comment by TexBlock** [comment]
non-replicable
