### ISSUE TITLE
Contraptions are invisible

### ISSUE THREAD

**Issue by joshua-pechan** [DM-Earth/create-fabric-dme-edition#8]
### Describe the Bug

Whenever I create a moving contraption it turns invisible. Ex minecart contraption, windmill, gantry

### Reproduction Steps

1. Create a contraption such as a minecart contraption, windmill, or gantry.

If it is a gantry or a windmill, it will only be invisible when it is moving

### Expected Result

I expected to see the contraption

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by RWRmrfrog** [comment]
Anyone know what's causing this? Is there any quick patches I could do to get this working again?

**Comment by TexBlock** [comment]
fixed in Patch 3
